export const constants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    USER_GROUPS_REQUEST: 'USER_GROUPS_REQUEST',
    USER_GROUPS_SUCCESS: 'USER_GROUPS_SUCCESS',
    USER_GROUPS_FAILURE: 'USER_GROUPS_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGOUT: 'USERS_LOGOUT',

    CHECK_AUTH_REQUEST: 'CHECK_AUTH_REQUEST',
    CHECK_AUTH_SUCCESS: 'CHECK_AUTH_SUCCESS',
    CHECK_AUTH_FAILURE: 'CHECK_AUTH_FAILURE',

    DELETE_REQUEST: 'USERS_DELETE_REQUEST',
    DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
    DELETE_FAILURE: 'USERS_DELETE_FAILURE',

    AUTOCOMPLETE_REQUEST: 'AUTOCOMPLETE_REQUEST',
    AUTOCOMPLETE_SUCCESS: 'AUTOCOMPLETE_SUCCESS',
    AUTOCOMPLETE_FAILURE: 'AUTOCOMPLETE_FAILURE',

    CREATE_PLACE_REQUEST: 'CREATE_PLACE_REQUEST',
    CREATE_PLACE_SUCCESS: 'CREATE_PLACE_SUCCESS',
    CREATE_PLACE_FAILURE: 'CREATE_PLACE_FAILURE',

    GET_PLACES_REQUEST: 'GET_PLACES_REQUEST',
    GET_PLACES_SUCCESS: 'GET_PLACES_SUCCESS',
    GET_PLACES_FAILURE: 'GET_PLACES_FAILURE',

    GET_GROUPS_REQUEST: 'GET_GROUPS_REQUEST',
    GET_GROUPS_SUCCESS: 'GET_GROUPS_SUCCESS',
    GET_GROUPS_FAILURE: 'GET_GROUPS_FAILURE',


    SEARCH_GROUPS_REQUEST: 'SEARCH_GROUPS_REQUEST',
    SEARCH_GROUPS_SUCCESS: 'SEARCH_GROUPS_SUCCESS',
    SEARCH_GROUPS_FAILURE: 'SEARCH_GROUPS_FAILURE',


    LOCAL_AUTOCOMPLETE_REQUEST: 'LOCAL_AUTOCOMPLETE_REQUEST',
    LOCAL_AUTOCOMPLETE_SUCCESS: 'LOCAL_AUTOCOMPLETE_SUCCESS',
    LOCAL_AUTOCOMPLETE_FAILURE: 'LOCAL_AUTOCOMPLETE_FAILURE',

    GET_CRITERIA_REQUEST: 'GET_CRITERIA_REQUEST',
    GET_CRITERIA_SUCCESS: 'GET_CRITERIA_SUCCESS',
    GET_CRITERIA_FAILURE: 'GET_CRITERIA_FAILURE',

    GET_GROUP_REQUEST: 'GET_GROUP_REQUEST',
    GET_GROUP_SUCCESS: 'GET_GROUP_SUCCESS',
    GET_GROUP_FAILURE: 'GET_GROUP_FAILURE',

    GROUP_MESSAGES_REQUEST: 'GROUP_MESSAGES_REQUEST',
    GROUP_MESSAGES_SUCCESS: 'GROUP_MESSAGES_SUCCESS',
    GROUP_MESSAGES_FAILURE: 'GROUP_MESSAGES_FAILURE',

    GET_LANGUAGES_REQUEST: 'GET_LANGUAGES_REQUEST',
    GET_LANGUAGES_SUCCESS: 'GET_LANGUAGES_SUCCESS',
    GET_LANGUAGES_FAILURE: 'GET_LANGUAGES_FAILURE',

    JOIN_GROUP_REQUEST: 'JOIN_GROUP_REQUEST',
    JOIN_GROUP_SUCCESS: 'JOIN_GROUP_SUCCESS',
    JOIN_GROUP_FAILURE: 'JOIN_GROUP_FAILURE'
};