# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the deployment branch
on:
  push:
    branches: [ deployment ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        sudo apt-get update && apt-get install -qy git curl libmcrypt-dev coreutils curl bash rsync openssh-client,
        yes | pecl install mcrypt-1.0.1,
        curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer,
        cd api,
        composer install --optimize-autoloader --no-dev,
        cp .env.example .env,
        php artisan key:generate,
        cd ../,
        rsync -crlOt -e ssh ./api/* ec2-user@ec2-15-236-238-84.eu-west-3.compute.amazonaws.com:/var/www/api.pmubet.com --progress,
        rsync -avzuhO -e ssh ./docker/recxml ec2-user@ec2-15-236-238-84.eu-west-3.compute.amazonaws.com:/var/www/docker --progress
